$(document).ready(function () { //Cuando el documento html este totalmente cargado
    $(".infoSectionEra1").toggleClass("showEra");
    $(".infoSectionEra2, .infoSectionEra3, .infoSectionEra4, .infoSectionEra5, .infoSectionEra6, .infoSectionEra7, .infoSectionEra8, .infoSectionEra9, .infoSectionEra10, .infoSectionEra11").toggleClass("hideEra");
    $("#era1").addClass("selectedEra");
    $("#era2, #era3, #era4, #era5, #era6, #era7, #era8, #era9, #era10, #era11").removeClass("selectedEra");
    $(".infoSectionDay1").toggleClass("showEra");
    $(".infoSectionDay2, .infoSectionDay3, .infoSectionDay4, .infoSectionDay5, .infoSectionDay6, .infoSectionDay7, .infoSectionDay8").toggleClass("hideEra");
    $("#day1").addClass("selectedEra");
    $("#day2, #day3, #day4, #day5, #day6, #day7, #day8").removeClass("selectedEra");
    $(".menu-toggle").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $(".nav-list").toggleClass("show");
        $(".bar:nth-child(1)").toggleClass("rotate-45");
        $(".bar:nth-child(2)").toggleClass("hide");
        $(".bar:nth-child(3)").toggleClass("rotate45");
    });
    $("#era1").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#era1").addClass("selectedEra");
        $("#era2, #era3, #era4, #era5, #era6, #era7, #era8, #era9, #era10, #era11").removeClass("selectedEra");
        $(".infoSectionEra1").addClass("showEra").removeClass("hideEra");
        $(".infoSectionEra2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra8").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra9").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra10").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra11").addClass("hideEra").removeClass("showEra");
    });
    $("#era2").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#era2").addClass("selectedEra");
        $("#era1, #era3, #era4, #era5, #era6, #era7, #era8, #era9, #era10, #era11").removeClass("selectedEra");
        $(".infoSectionEra1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra2").addClass("showEra").removeClass("hideEra");
        $(".infoSectionEra3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra8").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra9").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra10").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra11").addClass("hideEra").removeClass("showEra");
    });
    $("#era3").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#era3").addClass("selectedEra");
        $("#era1, #era2, #era4, #era5, #era6, #era7, #era8, #era9, #era10, #era11").removeClass("selectedEra");
        $(".infoSectionEra1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra3").addClass("showEra").removeClass("hideEra");
        $(".infoSectionEra4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra8").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra9").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra10").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra11").addClass("hideEra").removeClass("showEra");
    });
    $("#era4").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#era4").addClass("selectedEra");
        $("#era1, #era2, #era3, #era5, #era6, #era7, #era8, #era9, #era10, #era11").removeClass("selectedEra");
        $(".infoSectionEra1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra4").addClass("showEra").removeClass("hideEra");
        $(".infoSectionEra5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra8").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra9").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra10").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra11").addClass("hideEra").removeClass("showEra");
    });
    $("#era5").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#era5").addClass("selectedEra");
        $("#era1, #era2, #era3, #era4, #era6, #era7, #era8, #era9, #era10, #era11").removeClass("selectedEra");
        $(".infoSectionEra1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra5").addClass("showEra").removeClass("hideEra");
        $(".infoSectionEra6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra8").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra9").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra10").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra11").addClass("hideEra").removeClass("showEra");
    });
    $("#era6").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#era6").addClass("selectedEra");
        $("#era1, #era2, #era3, #era4, #era5, #era7, #era8, #era9, #era10, #era11").removeClass("selectedEra");
        $(".infoSectionEra1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra6").addClass("showEra").removeClass("hideEra");
        $(".infoSectionEra7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra8").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra9").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra10").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra11").addClass("hideEra").removeClass("showEra");
    });
    $("#era7").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#era7").addClass("selectedEra");
        $("#era1, #era2, #era3, #era4, #era5, #era6, #era8, #era9, #era10, #era11").removeClass("selectedEra");
        $(".infoSectionEra1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra7").addClass("showEra").removeClass("hideEra");
        $(".infoSectionEra8").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra9").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra10").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra11").addClass("hideEra").removeClass("showEra");
    });
    $("#era8").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#era8").addClass("selectedEra");
        $("#era1, #era2, #era3, #era4, #era5, #era6, #era7, #era9, #era10, #era11").removeClass("selectedEra");
        $(".infoSectionEra1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra8").addClass("showEra").removeClass("hideEra");
        $(".infoSectionEra9").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra10").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra11").addClass("hideEra").removeClass("showEra");
    });
    $("#era9").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#era9").addClass("selectedEra");
        $("#era1, #era2, #era3, #era4, #era5, #era6, #era7, #era8, #era10, #era11").removeClass("selectedEra");
        $(".infoSectionEra1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra8").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra9").addClass("showEra").removeClass("hideEra");
        $(".infoSectionEra10").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra11").addClass("hideEra").removeClass("showEra");
    });
    $("#era10").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#era10").addClass("selectedEra");
        $("#era1, #era2, #era3, #era4, #era5, #era6, #era7, #era8, #era9, #era11").removeClass("selectedEra");
        $(".infoSectionEra1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra8").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra9").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra10").addClass("showEra").removeClass("hideEra");
        $(".infoSectionEra11").addClass("hideEra").removeClass("showEra");
    });
    $("#era11").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#era11").addClass("selectedEra");
        $("#era1, #era2, #era3, #era4, #era5, #era6, #era7, #era8, #era9, #era10").removeClass("selectedEra");
        $(".infoSectionEra1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra8").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra9").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra10").addClass("hideEra").removeClass("showEra");
        $(".infoSectionEra11").addClass("showEra").removeClass("hideEra");
    });

    $("#day1").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#day1").addClass("selectedEra");
        $("#day2, #day3, #day4, #day5, #day6, #day7, #day8").removeClass("selectedEra");
        $(".infoSectionDay1").addClass("showEra").removeClass("hideEra");
        $(".infoSectionDay2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay8").addClass("hideEra").removeClass("showEra");
    });
    $("#day2").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#day2").addClass("selectedEra");
        $("#day1, #day3, #day4, #day5, #day6, #day7, #day8").removeClass("selectedEra");
        $(".infoSectionDay1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay2").addClass("showEra").removeClass("hideEra");
        $(".infoSectionDay3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay8").addClass("hideEra").removeClass("showEra");
    });
    $("#day3").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#day3").addClass("selectedEra");
        $("#day1, #day2, #day4, #day5, #day6, #day7, #day8").removeClass("selectedEra");
        $(".infoSectionDay1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay3").addClass("showEra").removeClass("hideEra");
        $(".infoSectionDay4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay8").addClass("hideEra").removeClass("showEra");
    });
    $("#day4").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#day4").addClass("selectedEra");
        $("#day1, #day2, #day3, #day5, #day6, #day7, #day8").removeClass("selectedEra");
        $(".infoSectionDay1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay4").addClass("showEra").removeClass("hideEra");
        $(".infoSectionDay5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay8").addClass("hideEra").removeClass("showEra");
    });
    $("#day5").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#day5").addClass("selectedEra");
        $("#day1, #day2, #day3, #day4, #day6, #day7, #day8").removeClass("selectedEra");
        $(".infoSectionDay1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay5").addClass("showEra").removeClass("hideEra");
        $(".infoSectionDay6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay8").addClass("hideEra").removeClass("showEra");
    });
    $("#day6").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#day6").addClass("selectedEra");
        $("#day1, #day2, #day3, #day4, #day5, #day7, #day8").removeClass("selectedEra");
        $(".infoSectionDay1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay6").addClass("showEra").removeClass("hideEra");
        $(".infoSectionDay7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay8").addClass("hideEra").removeClass("showEra");
    });
    $("#day7").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#day7").addClass("selectedEra");
        $("#day1, #day2, #day3, #day4, #day5, #day6, #day8").removeClass("selectedEra");
        $(".infoSectionDay1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay7").addClass("showEra").removeClass("hideEra");
        $(".infoSectionDay8").addClass("hideEra").removeClass("showEra");
    });
    $("#day8").click(function () { //Cuando haga click sobre el elemento con clase .menu-toggle
        $("#day8").addClass("selectedEra");
        $("#day1, #day2, #day3, #day4, #day5, #day6, #day7").removeClass("selectedEra");
        $(".infoSectionDay1").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay2").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay3").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay4").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay5").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay6").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay7").addClass("hideEra").removeClass("showEra");
        $(".infoSectionDay8").addClass("showEra").removeClass("hideEra");
    });
    
});

